export const denmCauseCodes = {
  1: "Traffic",
  2: "Accident",
  3: "Roadwork",
  6: "Adverse weather condition (slippery road)",
  9: "Surface Condition",
  10: "Obstacle On Road",
  11: "Animal On Road",
  12: "Human presence on the road",
  14: "Wrong way driving",
  15: "Rescue and recovery work",
  17: "Extreme weather condition",
  18: "Low visibility",
  19: "Adverse weather condition -Precipitation",
  26: "Slow vehicle",
  27: "Dangerous end of queue",
  91: "Vehicle breakdown",
  92: "Post crash",
  93: "Human problem",
  94: "Stationary vehicle",
  95: "Emergency vehicle approaching",
  96: "Dangerous curve",
  97: "Collision risk",
  98: "Signal violation",
  99: "Dangerous situation",
};
