name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SVV_GITHUB_ACTIONS_PUBLISHER_KEY }}
    - name: Configure Docker/GCP
      run: gcloud auth configure-docker
    - name: Create tag
      run: echo "IMAGE_TAG=$(date +%s)" >> "$GITHUB_ENV"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eu.gcr.io/nw-shared-w3ml/napcore-frontend:${{ env.IMAGE_TAG }}
    - name: Push docker image
      run: docker push eu.gcr.io/nw-shared-w3ml/napcore-frontend:${{ env.IMAGE_TAG }}
