name: Docker Image CI

permissions:
  contents: read
  id-token: write
  packages: write

on:
  push:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Google CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '446.0.1'
          project_id: ${{ vars.PROJECT_ID }}

      - name: Login to Artifact Registry
        run: gcloud auth configure-docker ${{ vars.REGIONAL_ARTIFACT_REGISTRY_URL }} --quiet

      - name: Create tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Build the Docker image
        run: docker build . -t napcore-frontend --file Dockerfile

      - name: Push docker image to GCP
        run: |
          docker tag napcore-frontend  ${{ vars.REGIONAL_ARTIFACT_REGISTRY_URL }}/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REGISTRY_REPOSITORY }}/napcore-frontend:${{ env.IMAGE_TAG }}
          docker push --all-tags ${{ vars.REGIONAL_ARTIFACT_REGISTRY_URL }}/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REGISTRY_REPOSITORY }}/napcore-frontend

      - name: Login to Github container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image to Github container registry
        run: |
          docker tag napcore-frontend ghcr.io/nordicwayinterchange/napcore-frontend:${{ env.IMAGE_TAG }}
          docker push --all-tags ghcr.io/nordicwayinterchange/napcore-frontend