name: Docker Image CI

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Build the Docker image
        run: docker build . -t napcore-frontend --file Dockerfile

      - name: Login to Github container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: "Github Actions"
          password: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Push docker image to Github container registry
        run: |
          docker tag napcore-frontend ghcr.io/nordicwayinterchange/napcore-frontend:${{ env.IMAGE_TAG }}
          docker push --all-tags ghcr.io/nordicwayinterchange/napcore-frontend